<a href="https://colab.research.google.com/github/25stu0613-dowon/Google-colab-guide/blob/main/colab_basic_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
python code 성적

In [2]:
# 학생 수
num_students = 5

# 학생 정보 저장 리스트
students = []

# 입력 받기
for i in range(num_students):
    print(f"\n{i+1}번째 학생 정보 입력")
    name = input("이름: ")

    # Function to get valid integer input for a subject
    def get_score(subject):
        while True:
            try:
                score_str = input(f"{subject} 점수: ")
                score = int(score_str)
                return score
            except ValueError:
                print("잘못된 입력입니다. 숫자를 입력해주세요.")

    korean = get_score("국어")
    math = get_score("수학")
    science = get_score("과학")

    student = {
        "이름": name,
        "국어": korean,
        "수학": math,
        "과학": science,
        "합계": korean + math + science,
        "평균": round((korean + math + science) / 3, 2)
    }
    students.append(student)

# 개인별 성적 출력
print("\n🧑‍🎓 학생별 성적")
print("-" * 40)
for s in students:
    print(f"이름: {s['이름']}, 국어: {s['국어']}, 수학: {s['수학']}, 과학: {s['과학']}, 합계: {s['합계']}, 평균: {s['평균']}")

# 과목별 합계 및 평균 계산
total_korean = sum(s['국어'] for s in students)
total_math = sum(s['수학'] for s in students)
total_science = sum(s['과학'] for s in students)

avg_korean = round(total_korean / num_students, 2)
avg_math = round(total_math / num_students, 2)
avg_science = round(total_science / num_students, 2)

# 과목별 총점 및 평균 출력
print("\n📊 과목별 총점 및 평균")
print("-" * 40)
print(f"국어 - 총점: {total_korean}, 평균: {avg_korean}")
print(f"수학 - 총점: {total_math}, 평균: {avg_math}")
print(f"과학 - 총점: {total_science}, 평균: {avg_science}")

1번째 학생 정보 입력
이름: dowon
국어 점수: 90
수학 점수: 90
과학 점수: 67

2번째 학생 정보 입력
이름: ddokddoki
국어 점수: 30
수학 점수: 20
과학 점수: 100

3번째 학생 정보 입력
이름: taa
국어 점수: 88
수학 점수: 22
과학 점수: 56

4번째 학생 정보 입력
이름: lucas
국어 점수: 49
수학 점수: 95
과학 점수: 98

5번째 학생 정보 입력
이름: ryley
국어 점수: 10
수학 점수: 77
과학 점수: 98

🧑‍🎓 학생별 성적
----------------------------------------
이름: dowon, 국어: 90, 수학: 90, 과학: 67, 합계: 247, 평균: 82.33
이름: ddokddoki, 국어: 30, 수학: 20, 과학: 100, 합계: 150, 평균: 50.0
이름: taa, 국어: 88, 수학: 22, 과학: 56, 합계: 166, 평균: 55.33
이름: lucas, 국어: 49, 수학: 95, 과학: 98, 합계: 242, 평균: 80.67
이름: ryley, 국어: 10, 수학: 77, 과학: 98, 합계: 185, 평균: 61.67

📊 과목별 총점 및 평균
----------------------------------------
국어 - 총점: 267, 평균: 53.4
수학 - 총점: 304, 평균: 60.8
과학 - 총점: 419, 평균: 83.8

In [3]:
import pandas as pd

# 1. 학생별 성적 데이터 입력
data = {
    "이름": ["dowon", "ddokddoki", "taa", "lucas", "rylev"],
    "국어": [90, 30, 88, 49, 10],
    "수학": [90, 20, 22, 95, 77],
    "과학": [67, 100, 56, 98, 98]
}

# 2. DataFrame 생성
df = pd.DataFrame(data)

# 3. 합계 및 평균 계산 열 추가
df["합계"] = df[["국어", "수학", "과학"]].sum(axis=1)
df["평균"] = round(df["합계"] / 3, 2)

# 4. 과목별 총점 및 평균 계산
subject_totals = df[["국어", "수학", "과학"]].sum()
subject_averages = round(df[["국어", "수학", "과학"]].mean(), 2)

# 5. 출력
print("🧑‍🎓 학생별 성적표")
display(df)

print("\n📊 과목별 총점")
display(subject_totals.to_frame(name="총점").T)

print("\n📊 과목별 평균")
display(subject_averages.to_frame(name="평균").T)

🧑‍🎓 학생별 성적표

          이름  국어  수학   과학   합계     평균
0      dowon  90  90   67  247  82.33
1  ddokddoki  30  20  100  150  50.00
2        taa  88  22   56  166  55.33
3      lucas  49  95   98  242  80.67
4      rylev  10  77   98  185  61.67

📊 과목별 총점

     국어   수학   과학
총점  267  304  419

📊 과목별 평균

      국어    수학    과학
평균  53.4  60.8  83.8